name: LyttleGravestone
version: '${projectVersion}'
main: com.lyttledev.lyttlegravestone.LyttleGravestone
api-version: '1.21'
authors:
  - ThatsATim
  - Stualyttle

softdepend: [Vault, LyttleScoreboardEconomy]